### PR TITLE
Added canvas subtle

### PR DESCRIPTION
**Pull request by auareyou**

### CODE REVIEW

**Comment by colebemis** [comment]
Do you want to update the `deprecated` variables to map to `canvas.subtle` instead of `neutral.subtle` in this PR?

**Comment by auareyou** [comment]
> Do you want to update the `deprecated` variables to map to `canvas.subtle` instead of `neutral.subtle` in this PR?

Ah yes! I'll do that today!

**Comment by simurai** [comment]
> Do you want to update the `deprecated` variables to map to `canvas.subtle` instead of `neutral.subtle` in this PR?

Maybe we can keep `neutral.subtle` for smaller things like hover state, counters, branch name, but change it for:

- `bg.secondary` -> `canvas.subtle`
- `bg.tertiary` -> `canvas.subtle`

**Comment by auareyou** [comment]
> > Do you want to update the `deprecated` variables to map to `canvas.subtle` instead of `neutral.subtle` in this PR?
> 
> Maybe we can keep `neutral.subtle` for smaller things like hover state, counters, branch name, but change it for:
> 
> * `bg.secondary` -> `canvas.subtle`
> * `bg.tertiary` -> `canvas.subtle`
> * `timeline.badgeBg` -> `canvas.subtle` (to cover the timeline border)

That makes sense! It's a good rule!

**Comment by auareyou** [comment]
I'd add, neutral subtle is for things that overlap with backgrounds

**Review by simurai — APPROVED** [review]
> That makes sense! It's a good rule!

Ok, added it here https://github.com/primer/primitives/pull/128/commits/fe47bf91806222032f04abdbde45ad0b2ecd292f. Let's test it. 🚢

**Pull request merged**
